version: '3'

services:
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.5.0
    ports:
      - "8474:8474"
      - "26379:26379"
      - "24222:24222"
    
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass testpassword
  
  nats:
    image: nats
    ports:
      - "4222:4222"
